// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test6-', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test6-', async function() {
    await driver.get("http://localhost:8000/")
    await driver.manage().window().setRect(1536, 800)
    await driver.findElement(By.linkText("web_app_test/")).click()
    await driver.findElement(By.linkText("src/")).click()
    await driver.findElement(By.id("num1")).click()
    await driver.findElement(By.id("num1")).sendKeys("hola ")
    await driver.findElement(By.id("num2")).click()
    await driver.findElement(By.id("num2")).sendKeys("djqrqf3-3")
    await driver.findElement(By.id("num1")).click()
    await driver.findElement(By.id("num1")).sendKeys("hola-33")
    await driver.findElement(By.css("button:nth-child(2)")).click()
    await driver.findElement(By.css("body")).click()
  })
})
